"""int_to_bigint

Revision ID: 5e9218233613
Revises: c6c9f49abcfb
Create Date: 2023-12-08 07:19:47.249519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e9218233613'
down_revision = 'c6c9f49abcfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_price_subscription', schema=None) as batch_op:
        batch_op.alter_column('start_timestamp',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('last_synced_timestamp',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_price_subscription', schema=None) as batch_op:
        batch_op.alter_column('last_synced_timestamp',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('start_timestamp',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
