"""state in subscriptions

Revision ID: b25ff65428c1
Revises: e9ecd5afba9a
Create Date: 2023-12-08 12:27:27.802128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25ff65428c1'
down_revision = 'e9ecd5afba9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Enum('DONE', 'PROCESSING', 'FAILED', name='taskstatus'), nullable=True))

    with op.batch_alter_table('token_price_subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Enum('DONE', 'PROCESSING', 'FAILED', name='taskstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_price_subscription', schema=None) as batch_op:
        batch_op.drop_column('state')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
