"""tp_subscription

Revision ID: c6c9f49abcfb
Revises: e33e4c64b7c7
Create Date: 2023-12-08 07:14:34.231578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6c9f49abcfb'
down_revision = 'e33e4c64b7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_price_subscription',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=72), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('time_interval', sa.Integer(), nullable=False),
    sa.Column('start_timestamp', sa.Integer(), nullable=False),
    sa.Column('last_synced_timestamp', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cache_options', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('cache_options')

    op.drop_table('token_price_subscription')
    # ### end Alembic commands ###
