"""init

Revision ID: d9c028691fd1
Revises: 
Create Date: 2023-12-06 09:07:43.700522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9c028691fd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=72), nullable=False),
    sa.Column('abi', mysql.JSON(), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('from_block', sa.Integer(), nullable=False),
    sa.Column('to_block', sa.Integer(), nullable=True),
    sa.Column('last_synced_block', sa.Integer(), nullable=True),
    sa.Column('block_difference', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    # ### end Alembic commands ###
