"""topics to topic

Revision ID: e33e4c64b7c7
Revises: d9c028691fd1
Create Date: 2023-12-06 09:25:11.044106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e33e4c64b7c7'
down_revision = 'd9c028691fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.Text(), nullable=True))
        batch_op.drop_column('topics')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topics', mysql.TEXT(), nullable=True))
        batch_op.drop_column('topic')

    # ### end Alembic commands ###
