"""is active in tp_subscription

Revision ID: e9ecd5afba9a
Revises: 5e9218233613
Create Date: 2023-12-08 08:44:37.203105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ecd5afba9a'
down_revision = '5e9218233613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_price_subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_price_subscription', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
